### ISSUE TITLE
你好，能否写一个makefile来编译jumsupplicant？

### ISSUE THREAD

**Issue by nature2608** [LGiki/luci-app-jmuSupplicant#1]
我用交叉编译提示很多错误无法进行下去，不知是否环境变量配置错误等问题，若有makefile可以一起与luci-app-jupsupplicant一起依赖。

**Comment by LGiki** [comment]
之前漏了这个issue，不好意思。
不清楚你是想编译[luci-app-jmusupplicant](https://github.com/LGiki/luci-app-jmuSupplicant)还是[jmuSupplicant](https://github.com/ShanQincheng/jmuSupplicant)。
如果是当前项目，即luci-app-jmusupplicant的话，可以到该项目的[release](https://github.com/LGiki/luci-app-jmuSupplicant/releases)页面下下载已经编译好的版本，luci相关的包基本都不会包含平台相关的二进制文件，所以基本上是全平台通用的。
如果是jmuSupplicant的话，之前帮忙改成了利用cmake生成Makefile再进行编译的方式，在README里面也介绍了相关的编译过程。作者之前也有个直接写Makefile编译的版本，可以翻一翻之前的commit。如果遇到什么错误，建议将相应的错误信息也同时提交到issue里面，这样比较方便进行讨论。

**Comment by nature2608** [comment]
你好，我的意思是编译jmusupplicant跟编译luci-app-jmusupplicant一样，可以用sdk编译成ipk软件包一样，可以不用配置环境变量等。

**Comment by LGiki** [comment]
原来如此，你的这个想法应该是可行的，可以直接利用 sdk 来编译 jmuSupplicant 并构建成一个 ipk 软件包。
不过我最近正忙着准备考研，暂时没有比较充分的时间来完成这个事情，我会尽量找时间来完成。

**Comment by nature2608** [comment]
考研加油！

**Comment by aiamadeus** [comment]
今天突然记起就写了下😂：https://github.com/openjmu/jmuSupplicant-OpenWrt-ipk

**Comment by nature2608** [comment]
> 今天突然记起就写了下😂：https://github.com/openjmu/jmuSupplicant-OpenWrt-ipk

大佬真猛！
