### ISSUE TITLE
没有luci界面出现

### ISSUE THREAD

**Issue by aiamadeus** [LGiki/luci-app-jmuSupplicant#2]
你好，我路由器是刷了openwrt 18.06.1，然后用的是lede-sdk-17.01.6-ar71xx-generic_gcc-5.4.0_musl-1.1.16.Linux-x86_64编译的。jmusupplicant可以正常使用，并且所在路径已经加进环境变量。编译出来的ipk文件安装后并没有luci界面出现。

**Comment by LGiki** [comment]
这个 Luci 模块会自动检测系统环境变量的路径下是否存在 jmusupplicant 的可执行文件，只有找到了才会显示在 Luci 页面中。你在 Luci 中无法找到这个页面的话，说明目前该模块无法找到 jmusupplicant 的可执行文件，所以它就不会在 Luci 中出现。

我猜测可能是你将 `jmusupplicant` 命名成了 `jmuSupplicant` ，即将 supplicant 的首字母大写了，而我在这个模块检测可执行文件的判断语句中只写了 jmusupplicant ，导致的程序无法找到对应的可执行文件。这是我的疏忽，没有在 README 中讲清楚。
你可以先检查一下是否将可执行文件命名成 `jmusupplicant`。
同时，可以 SSH 连接到路由器，直接输入 `jmusupplicant` 运行一下，看看能不能成功运行，以验证 `jmusupplicant` 所在的目录是否已经被加载到环境变量中。正常的结果应该如下：
```bash
root@OpenWrt:~# jmusupplicant
似乎没有输入认证帐号或密码.
尝试运行 'sudo ./jmuSupplicant --help' 获取使用方法。
```

**Comment by aiamadeus** [comment]
> 这个Luci模块会自动检测系统环境变量的路径下是否存在jmusupplicant的可执行文件，只有找到了才会显示在Luci页面中。你在Luci中无法找到这个页面的话，说明目前该模块无法找到jmusupplicant的可执行文件，所以它就不会在Luci中出现。
> 
> 我猜测可能是你将`jmusupplicant`命名成了`jmuSupplicant`，即将supplicant的首字母大写了，而我在这个模块检测可执行文件的判断语句中只写了jmusupplicant，导致的程序无法找到对应的可执行文件。这是我的疏忽，没有在README中讲清楚。
> 你可以先检查一下是否将可执行文件命名成`jmusupplicant`。
> 同时，可以SSH连接到路由器，直接输入`jmusupplicant`运行一下，看看能不能成功运行，以验证`jmusupplicant`所在的目录是否已经。被加载到环境变量中正常的结果应该如下：
> 
> ```shell
> root @ OpenWrt：〜＃ jmusupplicant
> 似乎没有输入认证帐号或密码。尝试 
> 运行' sudo ./jmuSupplicant --help '获取使用方法。
> ```

谢谢回复。我编译出来的二进制文件就是jmusupplicant，s并没有大写。jmusupplicant文件所在位置已加进环境变量，ssh连接后可以直接输jmusupplicant使用。

**Comment by LGiki** [comment]
我在 OpenWrt 18.06.1, r7258-5eb055306f 上进行了测试，把 jmusupplicant 的可执行文件放在了 `/bin/jmusupplicant` 之后是没有问题的，你可以尝试将 jmsupplicant 放到该路径试试。

**Comment by aiamadeus** [comment]
> 我在 OpenWrt 18.06.1, r7258-5eb055306f 上进行了测试，把 jmusupplicant 的可执行文件放在了 `/bin/jmusupplicant` 之后是没有问题的，你可以尝试将 jmsupplicant 放到该路径试试。

可以了，放到/bin就行了，自己建的文件夹不行，感谢。

**Comment by aiamadeus** [comment]
请问luci-app-jmusupplicant有办法显示当认证成功的时候能显示认证成功，认证失败的时候显示认证失败吗？另外，当luci-app-jmusupplicant认证成功后，能上网，但是ssh连接路由器，输入jmusupplicant，显示并没有在运行，希望能解答一下这是什么回事。

**Comment by LGiki** [comment]
目前 luci-app-jmuSupplicant 仅仅是对 [jmuSupplicant](https://github.com/ShanQincheng/jmuSupplicant) 的运行参数做一个简单的Web页面封装，暂时没有考虑实现认证结果的显示。主要也是因为我目前在准备考研，并没有那么多的时间来继续完善这个项目。
至于 luci-app-jmuSupplicant 认证成功后，输入 jmusupplicant 显示并没有在运行这个情况。你可以尝试使用 `ps` 指令查看当前正在运行的所有进程，看看有没有 jmusupplicant ，当然，这也可能这是本项目存在的一个 Bug。
